//
// Net.cpp
//
// $Id: //poco/1.4/Net/src/Net.cpp#10 $
//
// Library: Net
// Package: NetCore
// Module:  NetCore
//
// Copyright (c) 2005-2006, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#include "Poco/Net/Net.h"


#if defined(_WIN32) && defined(POCO_DLL)
	
#include "Poco/Net/SocketDefs.h"
#include "Poco/Net/NetException.h"

namespace Poco {
namespace Net {


void Net_API initializeNetwork()
	/// Initialize the network subsystem.
{
	WORD    version = MAKEWORD(2, 2);
	WSADATA data;
	if (WSAStartup(version, &data) != 0)
		throw NetException("Failed to initialize network subsystem");
}


void Net_API uninitializeNetwork()
	/// Uninitialize the network subsystem.
{
	WSACleanup();
}


} } // namespace Poco::Net


BOOL APIENTRY DllMain(HANDLE, DWORD reasonForCall, LPVOID)
{
	switch(reasonForCall)
	{
	case DLL_PROCESS_ATTACH:
		Poco::Net::initializeNetwork();
		break;
	case DLL_PROCESS_DETACH:
		Poco::Net::uninitializeNetwork();
	}
	return TRUE;
}


#endif // _WIN32 && POCO_DLL)
